### ISSUE TITLE
Temp units are non-configurable and defaults to C

### ISSUE THREAD

**Issue by Sheeri** [SunboX/mozweekend_AddOn_Demo#2]
I'm getting good at translating C to F in general, but it'd be nice if I could change settings...All I can do in settings is delete it, no preference there for C vs. F. 

It'd be great if it defaulted to units based on location or keyboard preference, but I don't mind having to change it....most of the world uses C so it's a reasonable default.

**Comment by SunboX** [comment]
Yep, I thought about that. Sadly there isn't a API yet to extend the Addon settings menu. And I'm too lazy to write a "addon" for that. :smirk:
Using the keyboard language is a good idea. I will keep this issue open. Any pull request is appreciated. :smirk: otherwise I may do this if I get some time.

**Comment by SunboX** [comment]
Should be fixed now. Can you plz re-install the whole addon? There should be a setting for temp unit and update interval now.
